### ISSUE TITLE
Can't get it to start with ConEmu and Cygwin OpenSSH, but Putty works

### ISSUE THREAD

**Issue by meffect** [GGLucas/cortex#30]
With Cygwin OpenSSH in ConEmu,

I run ./cortex and get this error:

Traceback (most recent call last):
  File "./cortex", line 970, in main
    interface.init()
  File "./cortex", line 552, in init
    curses.curs_set(0)
_curses.error: curs_set() returned ERR

If I do the same thing using Putty, cortext runs fine

I'm not sure why it's not working with the Cygwin/ConEmu setup

**Comment by ZaxonXP** [comment]
Tried the latest version on Linux Debian 9.6 stretch with xterm/uxterm/xfce-terminal with the same results:
```Traceback (most recent call last):
  File "./cortex", line 974, in main
    interface.init()
  File "./cortex", line 556, in init
    curses.curs_set(0)
_curses.error: curs_set() returned ERR
```
